version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: tobefit
    ports: 
      - "3360:3306"
    environment:
      MYSQL_DATABASE: tobefit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql/db:/data/db
   